import { getAuthUserId } from "@convex-dev/auth/server";
import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { internal } from "./_generated/api";

/** Generate a signed upload URL for file storage. */
export const generateUploadUrl = mutation({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");
    return await ctx.storage.generateUploadUrl();
  },
});

/** Save a file record after upload. */
export const saveFile = mutation({
  args: {
    sessionId: v.id("sessions"),
    name: v.string(),
    mimeType: v.string(),
    size: v.number(),
    storageId: v.string(),
    content: v.optional(v.string()),
  },
  handler: async (ctx, { sessionId, name, mimeType, size, storageId, content }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const user = await ctx.db.get(userId);
    const displayName = user?.name ?? user?.email ?? "Someone";

    const fileId = await ctx.db.insert("files", {
      sessionId,
      name,
      mimeType,
      size,
      storageId,
      content,
      uploadedBy: userId,
      uploadedByName: displayName,
      createdAt: Date.now(),
      isGenerated: false,
    });

    return fileId;
  },
});

/** Save a file generated by the agent. */
export const saveGeneratedFile = mutation({
  args: {
    sessionId: v.id("sessions"),
    name: v.string(),
    mimeType: v.string(),
    size: v.number(),
    content: v.string(),
  },
  handler: async (ctx, { sessionId, name, mimeType, size, content }) => {
    const fileId = await ctx.db.insert("files", {
      sessionId,
      name,
      mimeType,
      size,
      storageId: "generated",
      content,
      uploadedBy: (await ctx.auth.getUserIdentity())?.subject as any ?? "agent",
      uploadedByName: "AI",
      createdAt: Date.now(),
      isGenerated: true,
    });

    return fileId;
  },
});

/** List all files in a session. */
export const listSessionFiles = query({
  args: { sessionId: v.id("sessions") },
  handler: async (ctx, { sessionId }) => {
    const files = await ctx.db
      .query("files")
      .withIndex("by_session_created", (q) => q.eq("sessionId", sessionId))
      .order("desc")
      .collect();

    // Get download URLs for files that have storage ids
    const filesWithUrls = await Promise.all(
      files.map(async (f) => {
        let url: string | null = null;
        if (f.storageId && f.storageId !== "generated") {
          try {
            url = await ctx.storage.getUrl(f.storageId);
          } catch {
            // Storage file may have been deleted
          }
        }
        return {
          ...f,
          url,
        };
      })
    );

    return filesWithUrls;
  },
});

/** Get a single file by id. */
export const getFile = query({
  args: { fileId: v.id("files") },
  handler: async (ctx, { fileId }) => {
    const file = await ctx.db.get(fileId);
    if (!file) return null;

    let url: string | null = null;
    if (file.storageId && file.storageId !== "generated") {
      try {
        url = await ctx.storage.getUrl(file.storageId);
      } catch {
        // Storage file may have been deleted
      }
    }

    return { ...file, url };
  },
});

/** Delete a file. Only the uploader or driver can delete. */
export const deleteFile = mutation({
  args: { fileId: v.id("files") },
  handler: async (ctx, { fileId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const file = await ctx.db.get(fileId);
    if (!file) throw new Error("File not found");

    // Delete the storage object if it exists
    if (file.storageId && file.storageId !== "generated") {
      try {
        await ctx.storage.delete(file.storageId);
      } catch {
        // Ignore if already deleted
      }
    }

    await ctx.db.delete(fileId);
    return { success: true };
  },
});
